// Code generated by MockGen. DO NOT EDIT.
// Source: ./webook/internal/repository/sms_request.go
//
// Generated by this command:
//
//	mockgen -source=./webook/internal/repository/sms_request.go -package=repomocks -destination=./webook/internal/repository/mocks/sms_request.mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/geekbang/basic-go/webook/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsRequestRepository is a mock of SmsRequestRepository interface.
type MockSmsRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSmsRequestRepositoryMockRecorder
}

// MockSmsRequestRepositoryMockRecorder is the mock recorder for MockSmsRequestRepository.
type MockSmsRequestRepositoryMockRecorder struct {
	mock *MockSmsRequestRepository
}

// NewMockSmsRequestRepository creates a new mock instance.
func NewMockSmsRequestRepository(ctrl *gomock.Controller) *MockSmsRequestRepository {
	mock := &MockSmsRequestRepository{ctrl: ctrl}
	mock.recorder = &MockSmsRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsRequestRepository) EXPECT() *MockSmsRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSmsRequestRepository) Create(ctx context.Context, smsRequest domain.SmsRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, smsRequest)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSmsRequestRepositoryMockRecorder) Create(ctx, smsRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSmsRequestRepository)(nil).Create), ctx, smsRequest)
}

// FindRequestToRetry mocks base method.
func (m *MockSmsRequestRepository) FindRequestToRetry(ctx context.Context, config domain.SmsRequestRetryConfig, limit int) ([]domain.SmsRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRequestToRetry", ctx, config, limit)
	ret0, _ := ret[0].([]domain.SmsRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRequestToRetry indicates an expected call of FindRequestToRetry.
func (mr *MockSmsRequestRepositoryMockRecorder) FindRequestToRetry(ctx, config, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRequestToRetry", reflect.TypeOf((*MockSmsRequestRepository)(nil).FindRequestToRetry), ctx, config, limit)
}

// MarkAsRetryFailed mocks base method.
func (m *MockSmsRequestRepository) MarkAsRetryFailed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRetryFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRetryFailed indicates an expected call of MarkAsRetryFailed.
func (mr *MockSmsRequestRepositoryMockRecorder) MarkAsRetryFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRetryFailed", reflect.TypeOf((*MockSmsRequestRepository)(nil).MarkAsRetryFailed), ctx, id)
}

// MarkAsRetrySucceeded mocks base method.
func (m *MockSmsRequestRepository) MarkAsRetrySucceeded(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRetrySucceeded", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRetrySucceeded indicates an expected call of MarkAsRetrySucceeded.
func (mr *MockSmsRequestRepositoryMockRecorder) MarkAsRetrySucceeded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRetrySucceeded", reflect.TypeOf((*MockSmsRequestRepository)(nil).MarkAsRetrySucceeded), ctx, id)
}
