// Code generated by MockGen. DO NOT EDIT.
// Source: ./webook/pkg/rate_counter/types.go
//
// Generated by this command:
//
//	mockgen -source=./webook/pkg/rate_counter/types.go -package=rate_counter -destination=./webook/pkg/rate_counter/mocks/rate_counter.mock.go
//

// Package rate_counter is a generated GoMock package.
package rate_counter

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRateCounter is a mock of RateCounter interface.
type MockRateCounter struct {
	ctrl     *gomock.Controller
	recorder *MockRateCounterMockRecorder
}

// MockRateCounterMockRecorder is the mock recorder for MockRateCounter.
type MockRateCounterMockRecorder struct {
	mock *MockRateCounter
}

// NewMockRateCounter creates a new mock instance.
func NewMockRateCounter(ctrl *gomock.Controller) *MockRateCounter {
	mock := &MockRateCounter{ctrl: ctrl}
	mock.recorder = &MockRateCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateCounter) EXPECT() *MockRateCounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRateCounter) Add(matched bool) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", matched)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRateCounterMockRecorder) Add(matched any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRateCounter)(nil).Add), matched)
}

// StartExpireJob mocks base method.
func (m *MockRateCounter) StartExpireJob(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExpireJob", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartExpireJob indicates an expected call of StartExpireJob.
func (mr *MockRateCounterMockRecorder) StartExpireJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExpireJob", reflect.TypeOf((*MockRateCounter)(nil).StartExpireJob), ctx)
}

// MockRateCounterWithAccessToAccumulatedCount is a mock of RateCounterWithAccessToAccumulatedCount interface.
type MockRateCounterWithAccessToAccumulatedCount struct {
	ctrl     *gomock.Controller
	recorder *MockRateCounterWithAccessToAccumulatedCountMockRecorder
}

// MockRateCounterWithAccessToAccumulatedCountMockRecorder is the mock recorder for MockRateCounterWithAccessToAccumulatedCount.
type MockRateCounterWithAccessToAccumulatedCountMockRecorder struct {
	mock *MockRateCounterWithAccessToAccumulatedCount
}

// NewMockRateCounterWithAccessToAccumulatedCount creates a new mock instance.
func NewMockRateCounterWithAccessToAccumulatedCount(ctrl *gomock.Controller) *MockRateCounterWithAccessToAccumulatedCount {
	mock := &MockRateCounterWithAccessToAccumulatedCount{ctrl: ctrl}
	mock.recorder = &MockRateCounterWithAccessToAccumulatedCountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateCounterWithAccessToAccumulatedCount) EXPECT() *MockRateCounterWithAccessToAccumulatedCountMockRecorder {
	return m.recorder
}

// AccumulatedCount mocks base method.
func (m *MockRateCounterWithAccessToAccumulatedCount) AccumulatedCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccumulatedCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// AccumulatedCount indicates an expected call of AccumulatedCount.
func (mr *MockRateCounterWithAccessToAccumulatedCountMockRecorder) AccumulatedCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccumulatedCount", reflect.TypeOf((*MockRateCounterWithAccessToAccumulatedCount)(nil).AccumulatedCount))
}

// Add mocks base method.
func (m *MockRateCounterWithAccessToAccumulatedCount) Add(matched bool) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", matched)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRateCounterWithAccessToAccumulatedCountMockRecorder) Add(matched any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRateCounterWithAccessToAccumulatedCount)(nil).Add), matched)
}

// StartExpireJob mocks base method.
func (m *MockRateCounterWithAccessToAccumulatedCount) StartExpireJob(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExpireJob", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartExpireJob indicates an expected call of StartExpireJob.
func (mr *MockRateCounterWithAccessToAccumulatedCountMockRecorder) StartExpireJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExpireJob", reflect.TypeOf((*MockRateCounterWithAccessToAccumulatedCount)(nil).StartExpireJob), ctx)
}
